//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adatum.Portal {
    
    
    public partial class Default {
        
        /// <summary>
        /// DefaultScriptManager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager DefaultScriptManager;
        
        /// <summary>
        /// TooltipInformation2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Samples.Web.UI.Controls.TooltipInformation TooltipInformation2;
        
        /// <summary>
        /// TooltipInformation4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Samples.Web.UI.Controls.TooltipInformation TooltipInformation4;
    }
}
