//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TooltipText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TooltipText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TooltipText", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint: The type and value of the Admin claim are used to map a claim issued by your identity provider to both the Administrator and ShipmentCreator roles in Fabrikam Shipping..
        /// </summary>
        internal static string AdminClaimHint {
            get {
                return ResourceManager.GetString("AdminClaimHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint: This is the public key used to validate the signature of tokens from the identity provider. You can find this key in the FederationMetada.xml file..
        /// </summary>
        internal static string CertificateHint {
            get {
                return ResourceManager.GetString("CertificateHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint: Your can now try out your newly configured tenant in the Fabrikam Shipping application..
        /// </summary>
        internal static string CompletedHint {
            get {
                return ResourceManager.GetString("CompletedHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint: this field is optional. If provided it will map a claim issued by your identity provider to the CostCenter claim that Fabrikam Shipping recognizes..
        /// </summary>
        internal static string CostCenterHint {
            get {
                return ResourceManager.GetString("CostCenterHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint: This value must match the EntityID declared by your issuer. You can find this value declared in your issuer&apos;s FederationMetadata.xml file..
        /// </summary>
        internal static string EntityIDHint {
            get {
                return ResourceManager.GetString("EntityIDHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint: These options demonstrate how to configure an issuer either by using the FederationMetadata.xml document, or by providing the necessary configuration data manually..
        /// </summary>
        internal static string IssuerConfigurationIPHint {
            get {
                return ResourceManager.GetString("IssuerConfigurationIPHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint: This demonstrates how to configure your partner organization to use one of the social identity providers. This list is created by querying ACS for a list of social identity providers associated with the Fabrikam Shipping Enrollment relying party..
        /// </summary>
        internal static string IssuerConfigurationSIPHint {
            get {
                return ResourceManager.GetString("IssuerConfigurationSIPHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint:Tenants can use either their own identity provider, or choose to use one of the social identity providers such as Windows Live ID or Google that are supported by ACS..
        /// </summary>
        internal static string IssuerTypeHint {
            get {
                return ResourceManager.GetString("IssuerTypeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint: This is the UR Lof your identity provider&apos;s sign-in page..
        /// </summary>
        internal static string SignInAddressHint {
            get {
                return ResourceManager.GetString("SignInAddressHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint: This sample does not implement user and role management functionality for organizations using social identity providers. Each of these organizations has just a single user in the sample..
        /// </summary>
        internal static string SIPAdminHint {
            get {
                return ResourceManager.GetString("SIPAdminHint", resourceCulture);
            }
        }
    }
}
