//-----------------------------------------------------------------------------
//
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
//
// Copyright (c) Microsoft Corporation. All rights reserved.
//
//
//-----------------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute( "System.ServiceModel", "3.0.0.0" )]
[System.ServiceModel.ServiceContractAttribute( ConfigurationName = "IService1" )]
public interface IService1
{

    [System.ServiceModel.OperationContractAttribute( Action = "http://tempuri.org/IService1/Echo", ReplyAction = "http://tempuri.org/IService1/EchoResponse" )]
    string Echo( string value );
}

[System.CodeDom.Compiler.GeneratedCodeAttribute( "System.ServiceModel", "3.0.0.0" )]
public interface IService1Channel : IService1, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute( "System.ServiceModel", "3.0.0.0" )]
public partial class Service1Client : System.ServiceModel.ClientBase<IService1>, IService1
{

    public Service1Client()
    {
    }

    public Service1Client( string endpointConfigurationName ) :
        base( endpointConfigurationName )
    {
    }

    public Service1Client( string endpointConfigurationName, string remoteAddress ) :
        base( endpointConfigurationName, remoteAddress )
    {
    }

    public Service1Client( string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress ) :
        base( endpointConfigurationName, remoteAddress )
    {
    }

    public Service1Client( System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress ) :
        base( binding, remoteAddress )
    {
    }

    public string Echo( string value )
    {
        return base.Channel.Echo( value );
    }
}
