//===============================================================================
// Microsoft patterns & practices
// Cliams Identity Guide V2
//===============================================================================
// Copyright © Microsoft Corporation.  All rights reserved.
// This code released under the terms of the 
// Microsoft patterns & practices license (http://claimsid.codeplex.com/license)
//===============================================================================


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOrder.OrderTracking.Client.OrderTrackingService
{
    using System.CodeDom.Compiler;
    using System.Diagnostics;
    using System.ServiceModel;
    using System.ServiceModel.Channels;
    using System.ServiceModel.Security;
    using AOrder.OrderTracking.Contracts.Data;

    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName = "OrderTrackingService.IOrderTrackingService")]
    public interface IOrderTrackingService
    {
        [OperationContract(Action = "http://tempuri.org/IOrderTrackingService/GetAllOrders", ReplyAction = "http://tempuri.org/IOrderTrackingService/GetAllOrdersResponse")]
        [FaultContract(typeof(SecurityAccessDeniedException), Action = "http://tempuri.org/IOrderTrackingService/GetAllOrdersSecurityAccessDeniedExceptio" +
                                                                       "nFault", Name = "SecurityAccessDeniedException", Namespace = "http://schemas.datacontract.org/2004/07/System.ServiceModel.Security")]
        Order[] GetAllOrders();

        [OperationContract(Action = "http://tempuri.org/IOrderTrackingService/GetOrdersFromMyOrganization", ReplyAction = "http://tempuri.org/IOrderTrackingService/GetOrdersFromMyOrganizationResponse")]
        [FaultContract(typeof(SecurityAccessDeniedException), Action = "http://tempuri.org/IOrderTrackingService/GetOrdersFromMyOrganizationSecurityAcces" +
                                                                       "sDeniedExceptionFault", Name = "SecurityAccessDeniedException", Namespace = "http://schemas.datacontract.org/2004/07/System.ServiceModel.Security")]
        Order[] GetOrdersFromMyOrganization();
    }

    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface IOrderTrackingServiceChannel : IOrderTrackingService, IClientChannel
    {
    }

    [DebuggerStepThrough]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public class OrderTrackingServiceClient : ClientBase<IOrderTrackingService>, IOrderTrackingService
    {
        public OrderTrackingServiceClient()
        {
        }

        public OrderTrackingServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public OrderTrackingServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public OrderTrackingServiceClient(string endpointConfigurationName, EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public OrderTrackingServiceClient(Binding binding, EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public Order[] GetAllOrders()
        {
            return this.Channel.GetAllOrders();
        }

        public Order[] GetOrdersFromMyOrganization()
        {
            return this.Channel.GetOrdersFromMyOrganization();
        }
    }
}