//-----------------------------------------------------------------------------
//
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
//
// Copyright (c) Microsoft Corporation. All rights reserved.
//
//
//-----------------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute( "System.ServiceModel", "3.0.0.0" )]
[System.ServiceModel.ServiceContractAttribute( ConfigurationName = "IClaimsAwareWebService" )]
public interface IClaimsAwareWebService
{

    [System.ServiceModel.OperationContractAttribute( Action = "http://tempuri.org/IClaimsAwareWebService/ComputeResponse", ReplyAction = "http://tempuri.org/IClaimsAwareWebService/ComputeResponseResponse" )]
    string ComputeResponse( string input );
}

[System.CodeDom.Compiler.GeneratedCodeAttribute( "System.ServiceModel", "3.0.0.0" )]
public interface IClaimsAwareWebServiceChannel : IClaimsAwareWebService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute( "System.ServiceModel", "3.0.0.0" )]
public partial class ClaimsAwareWebServiceClient : System.ServiceModel.ClientBase<IClaimsAwareWebService>, IClaimsAwareWebService
{

    public ClaimsAwareWebServiceClient()
    {
    }

    public ClaimsAwareWebServiceClient( string endpointConfigurationName ) :
        base( endpointConfigurationName )
    {
    }

    public ClaimsAwareWebServiceClient( string endpointConfigurationName, string remoteAddress ) :
        base( endpointConfigurationName, remoteAddress )
    {
    }

    public ClaimsAwareWebServiceClient( string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress ) :
        base( endpointConfigurationName, remoteAddress )
    {
    }

    public ClaimsAwareWebServiceClient( System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress ) :
        base( binding, remoteAddress )
    {
    }

    public string ComputeResponse( string input )
    {
        return base.Channel.ComputeResponse( input );
    }
}
